import {
  LayoutDashboard,
  Package,
  Truck,
  Users,
  Map,
  Settings,
  Search,
  Filter,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  Check,
  X,
  TriangleAlert,
  Clock,
  MapPin,
  Bell,
  LogOut,
  Plus,
  ArrowRight,
  ArrowUpRight,
  Route,
  Gauge,
  Scale,
  Layers,
  User,
  Phone,
  Calendar,
  Sparkles,
  Inbox,
  RefreshCw,
  MoreHorizontal,
  Eye,
  ShieldCheck,
  Activity,
  Target,
  Flag,
  Download,
  Minus,
  type LucideIcon,
} from 'lucide-react';

/** Stable name → lucide component map so the app references names, not imports. */
export const ICONS = {
  dashboard: LayoutDashboard,
  package: Package,
  truck: Truck,
  users: Users,
  map: Map,
  settings: Settings,
  search: Search,
  filter: Filter,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  check: Check,
  x: X,
  alert: TriangleAlert,
  clock: Clock,
  mapPin: MapPin,
  bell: Bell,
  logout: LogOut,
  plus: Plus,
  arrowRight: ArrowRight,
  arrowUpRight: ArrowUpRight,
  route: Route,
  gauge: Gauge,
  scale: Scale,
  layers: Layers,
  user: User,
  phone: Phone,
  calendar: Calendar,
  sparkles: Sparkles,
  inbox: Inbox,
  refresh: RefreshCw,
  more: MoreHorizontal,
  eye: Eye,
  shield: ShieldCheck,
  activity: Activity,
  target: Target,
  flag: Flag,
  download: Download,
  minus: Minus,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;
